#
# Copyright IBM Corp. 2024, 2025
#
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applications.assetcatalog.name }}-svc
  namespace: {{ default "control-plane" .Release.Namespace }}
spec:
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: http
  selector:
    app: {{ .Values.applications.assetcatalog.name }}
  type: ClusterIP
---