#
# Copyright IBM Corp. 2024, 2025
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.applications.assetcatalog.name }}-config
data:
  APICP_STORE_ASSETS_HOST: {{ .Values.applications.datastore.name }}-lb
  APICP_STORE_ASSETS_PORT: "9200"
  APICP_STORE_ASSETS_USERNAME: "admin"
  APICP_STORE_ASSETS_PASSWORD: "MyPassword@123"
  APICP_STORE_ASSETS_ENABLE_SSL: "true"
  APICP_STORE_ASSETS_KEYSTORE_FILE_PATH: "/certs/keystore-ac.jks"
  APICP_STORE_ASSETS_KEYSTORE_PASSWORD: "webmethods"
  APICP_STORE_ASSETS_KEYSTORE_ALIAS_NAME: "webmethods"
  APICP_STORE_ASSETS_TRUSTSTORE_FILE_PATH: "/certs/truststore-ac.jks"
  APICP_STORE_ASSETS_TRUSTSTORE_PASSWORD: "webmethods"


  APICP_ENGINE_ENDPOINT: "https://{{ .Values.applications.engine.name }}-svc:8443"
  APICP_AUTH_JWKS_URI: "https://{{ .Values.applications.ingress.name }}-svc:8443/api/ingress/v1/discovery/keys"
  JAVA_OPTS: "-Xms256m -Xmx256m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/asset_catalog_heap_dump.hprof"

  SERVER_PORT: "8443"
  SERVER_SSL_ENABLED: "true"
  SERVER_SSL_KEY_ALIAS: "webmethods"
  SERVER_SSL_KEY_PASSWORD: "webmethods"
  SERVER_SSL_KEY_STORE: "/certs/keystore-ac.jks"
  SERVER_SSL_KEY_STORE_PASSWORD: "webmethods"
  SERVER_SSL_KEY_STORE_TYPE: "JKS"

  SERVER_SSL_TRUST_STORE: "/certs/truststore-ac.jks"
  SERVER_SSL_TRUST_STORE_PASSWORD: "webmethods"
  SERVER_SSL_CLIENT_AUTH: "NEED"
---
