#
# Copyright IBM Corp. 2024, 2025
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applications.assetcatalog.name }}
  namespace: {{ default "control-plane" .Release.Namespace }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.applications.assetcatalog.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.applications.assetcatalog.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.applications.assetcatalog.name }}
        date: "{{ now | unixEpoch }}"
    spec:
      automountServiceAccountToken: false
      volumes:
      - name: certs
        secret:
          secretName: {{ .Values.secrets.certs.name }}
      containers:
      - image: {{ .Values.applications.assetcatalog.imageName }}:{{ .Values.applications.assetcatalog.imageTag }}
        name: {{ .Values.applications.assetcatalog.name }}
        volumeMounts:
        - name: certs
          mountPath: {{ .Values.secrets.certs.mountPath }}
          readOnly: true
        envFrom:
        - configMapRef:
            name: {{ .Values.applications.assetcatalog.name }}-config
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1724
        resources:
          limits:
            cpu: {{ .Values.applications.assetcatalog.resources.limits.cpu }}
            memory: {{ .Values.applications.assetcatalog.resources.limits.memory }}
          requests:
            cpu: {{ .Values.applications.assetcatalog.resources.requests.cpu }}
            memory: {{ .Values.applications.assetcatalog.resources.requests.memory }}
        ports:
          - containerPort: 8443
            name: http
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "curl -fk -s --cert /certs/ac-cert.pem --key /certs/ac-key.pem  https://localhost:8443/api/assetcatalog/health/readiness || exit 1"
          initialDelaySeconds: 100
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 15
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "curl -fk -s --cert /certs/ac-cert.pem --key /certs/ac-key.pem  https://localhost:8443/api/assetcatalog/health/liveness || exit 1"
          initialDelaySeconds: 100
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 15
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
          - name: regcred
---