#
# Copyright IBM Corp. 2024, 2025
#
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applications.engine.name }}-svc
  namespace: {{ default "control-plane" .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: 8443

  selector:
    app: {{ .Values.applications.engine.name }}
  type: ClusterIP
---