#
# Copyright IBM Corp. 2024, 2025
#
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applications.ingress.name }}-svc
  namespace: {{ default "control-plane" .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: internal # Only for the JWT related internal communication.
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.applications.ingress.name }}
  type: ClusterIP
---