#
# Copyright IBM Corp. 2024, 2025
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.applications.ui.name }}-config
data:
  APICP_ENGINE_ENDPOINT: "https://{{ .Values.applications.engine.name }}-svc:8443"
  APICP_ASSET_CATALOG_ENDPOINT: "https://{{ .Values.applications.assetcatalog.name }}-svc:8443"
  APICP_AUTH_JWKS_URI: "https://{{ .Values.applications.ingress.name }}-svc:8443/api/ingress/v1/discovery/keys"
  SPRING_CODEC_MAX_IN_MEMORY_SIZE:  "{{ .Values.applications.ui.springCodecMaxMemorySize }}"
  # JAVA_OPTS: "-Xms256m -Xmx256m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/ui_heap_dump.hprof"

  SERVER_PORT: "8443"
  SERVER_SSL_ENABLED: "true"
  SERVER_SSL_KEY_ALIAS: "webmethods"
  SERVER_SSL_KEY_PASSWORD: "webmethods"
  SERVER_SSL_KEY_STORE: "/certs/keystore-ui.jks"
  SERVER_SSL_KEY_STORE_PASSWORD: "webmethods"
  SERVER_SSL_KEY_STORE_TYPE: "JKS"
  SERVER_SSL_TRUST_STORE: "/certs/truststore-ui.jks"
  SERVER_SSL_TRUST_STORE_PASSWORD: "webmethods"
  SERVER_SSL_CLIENT_AUTH: "NEED"


  OTEL_JAVAAGENT_ENABLED: "{{ .Values.applications.jaegertracing.enabled }}"
  {{- if .Values.applications.jaegertracing.enabled }}
  LOGGING_LEVEL_COM_SOFTWAREAG_CONTROLPLANE: "{{ .Values.applications.ui.logLevel }}"
  OTEL_METRICS_EXPORTER: "none"
  JAVA_OPTS: "-Dotel.exporter.otlp.endpoint=http://{{ .Values.applications.jaegertracing.name }}-svc:{{ .Values.applications.jaegertracing.port }} -Dotel.resource.attributes=service.name={{ .Values.applications.ui.name }}"
  {{- end }}
  {{- if .Values.applications.gainsight.enabled }}
  APICP_UI_TENANT_CLOUD_PROVIDER: "{{ .Values.applications.gainsight.tenant.cloudProvider }}"
  APICP_UI_TENANT_REGION_NAME: "{{ .Values.applications.gainsight.tenant.region }}"
  APICP_UI_TENANT_PLAN:  "{{ .Values.applications.gainsight.tenant.plan }}"
  APICP_UI_TENANT_CUSTOMER_NAME: "{{ .Values.applications.gainsight.tenant.name }}"
  APICP_UI_TENANT_COMPANY_NAME: "{{ .Values.applications.gainsight.tenant.name }}"
  APICP_UI_TENANT_STAGE_NAME: "{{ .Values.applications.gainsight.tenant.stage }}"
  APICP_UI_TENANT_GAINSIGHT_KEY: "{{ .Values.applications.gainsight.tenant.key }}"
  {{- end }}
---